export const userList=[
    {
        name:"sideral",
        email:"fracasado@gmail.com",
        id:1
    },
    {
        name:"buty",
        email:"fracasado2@gmail.com",
        id:2
    }
    ,
    {
        name:"macarius",
        email:"fracasado3@gmail.com",
        id:3
    },
    {
        name:"usuario",
        email:"normal@gmail.com",
        id:4
    }
]